### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue#3092]
- [x] 1.x -> 2.0 full change log
- [x] 1.x -> 2.0 upgrade guide
- [x] [Update vuejs.org to reflect 2.0 changes](https://github.com/vuejs/vuejs.org/issues/319)
- [x] [High-level guide on using `render` in 2.0](https://github.com/vuejs/vuejs.org/blob/2.0/src/guide/render-function.md)
- [x] [Documentation for the `vue-server-renderer` package](https://github.com/vuejs/vue/blob/next/packages/vue-server-renderer/README.md)
- [x] High-level guide on using SSR in 2.0
- [x] [Documentation for the `vue-template-compiler` package](https://github.com/vuejs/vue/blob/next/packages/vue-template-compiler/README.md)
- [x] vue-router 2.0 docs
- [x] vuex 2.0 docs

**Comment by ziqianghe** [comment]
add oil

**Comment by MeiYuanChen** [comment]
vue-server-renderer can solve 'seo' question?

**Comment by stylehuan** [comment]
I also need to server-renderer

**Comment by sharp-c** [comment]
I wonder when we can have some documentations on vue server side rendering, thank you.

**Comment by rajibahmed** [comment]
@yyx990803  and @LinusBorg I would love to help you guys somehow ( docs or anything) ...

**Comment by chrisvfritz** [comment]
@stylehuan @sharp-c As it's listed, rest assured we will be documenting server side rendering. 😉  In the meantime, you might enjoy browsing [these tests](https://github.com/vuejs/vue/tree/next/test/ssr).

@rajibahmed If you'd like to help, we'd love feedback on the [updated guide](https://github.com/vuejs/vuejs.org/issues/319). Note that the transition system page is out of date, but everything else should be current with the latest beta.

**Comment by amirrustam** [comment]
@MeiYuanChen Regarding your SEO worries, I'm under the impression that Google search crawlers have been able to understand Javascript. They announced this change back in 2014: https://webmasters.googleblog.com/2014/05/understanding-web-pages-better.html

Google is the dominate search engine in the Americas, Europe, Middle East and rest of Asia. The only exceptions are Russia and China. More than half of search traffic in China flows through Baidu, which does not interpret Javascript with their crawlers. Yandex, is the dominate engine in Russia, and they started crawling Javascript in pages since last year: https://yandex.ru/blog/webmaster/21369

So server-side rendering for sake SEO somewhat depends on your site's audience, and hopefully the info I provided helps. With that said, any server-side rendering that returns pre-rendered plain HTML or text content can be crawled by searchbots. `vue-server-renderer` will help with this, and actually @yyx990803 mentioned SEO as motivation for Vue on server-side when the issue was brought up: https://github.com/vuejs/vue/issues/114#issuecomment-35460192

**Comment by blocka** [comment]
Server side rendering is also needed for metatags (think facebook, etc.)

**Comment by amirrustam** [comment]
@blocka Yes. Also I came back to add that Google's crawlers are not full-proof JS renderers. They can't be fully be trusted yet to process your JS like you would think. Relevant: http://searchengineland.com/can-now-trust-google-crawl-ajax-sites-235267

So the new vue-server-renderer is greatly appreciated.

**Comment by elithrar** [comment]
As part of a migration to 2.0, I ported some 2-way filters on `v-model` to custom components with `v-bind:value` + emitting an input event - referring to http://rc.vuejs.org/guide/components.html#Form-Input-Components-using-Custom-Events

Two parts:
* I'd love to submit a simple "2 way filter to custom component" example, especially after having read the filter issue
* What *isn't* clear in the 2.0 changelog is why this approach doesn't work on 1.0 (which should also be documented, unless I've missed it, which is entirely possible)

**Comment by LinusBorg** [comment]
> What isn't clear in the 2.0 changelog is why this approach doesn't work on 1.0

...because in 1.0 you can use `.sync`. the "v-model on component" feature was developed for 2.0 to provide a mechanism to "sync", but only in cases where it makes sense (emulating inputs and v-model behavior)

**Comment by elithrar** [comment]
@LinusBorg Oh, derp. Of course. Is there an upgrade guide WIP - not seeing anything in https://github.com/vuejs/vuejs.org/tree/2.0/src/guide - I'd definitely want to contribute/cover that.

**Comment by chrisvfritz** [comment]
@elithrar The closest thing we have to upgrade guide currently is in the [2.0 changes](https://github.com/vuejs/vue/issues/2873#event-757546349) issue (see `Other Breaking Changes` and `Upgrade Tips`), but we will be building a real one prior to final release. 😃  It would actually be a great help if you could compile a list of things you'd like to see covered beyond what's already in that issue.

**Comment by LinusBorg** [comment]
> It would actually be a great help if you could compile a list of things you'd like to see covered beyond what's already in that issue.

Indeed. We may be blind to some spots as we are too familiar with both versions ...

**Comment by elithrar** [comment]
OK, so here seems as good as any place to cover some additional migration guide requests:

- [ ] How to migrate from Vue 1.0's 2-way filters to a a custom component - [this thread](https://github.com/vuejs/vue/issues/2756) provides evidence of a need.
- [ ] A more comprehensive Lifecycle Hook guide (ready -> mounted caveats, given how common ready usage is)
- [ ] Replacing debounce with your own implementation - partially covered [here](https://github.com/vuejs/vue/issues/2873) but definitely needs to be clearly featured in the docs.

**Comment by srodriki** [comment]
@yyx990803 I'd love to contribute with Vue by generating a Spanish translation of the guides. Would this be something you would be interested in having? 

Cheers!

**Comment by chrisvfritz** [comment]
@srodriki Definitely! See https://github.com/vuejs/vuejs.org/issues/308.

**Comment by zigomir** [comment]
vue-router 2.0 docs & vuex 2.0 docs are done, right? 🎉

**Comment by LinusBorg** [comment]
Yep.

**Comment by chrisvfritz** [comment]
@elithrar I'm currently developing those two-filters to components examples you talked about. You mentioned you might have some good examples to share?

**Comment by elithrar** [comment]
@chrisvfritz - here's a quick example of how I'm using it - https://gist.github.com/elithrar/659f531e574c46bb3bb8114045b437dct - custom v-model component w/ debounce inside.

**Comment by LinusBorg** [comment]
your gist link gives me 404

**Comment by elithrar** [comment]
@LinusBorg fixed.

**Comment by chrisvfritz** [comment]
Thanks @elithrar! I just added [a section on two-way filters specifically](http://vuejs.org/guide/migration.html#Two-Way-Filters-deprecated) to the migration guide. Would love to hear your thoughts!

**Comment by elithrar** [comment]
@chrisvfritz Great write-up - breaking it down into Vue 1 -> Vue 2 steps does a great job of illustrating the changes required (and the benefits of the custom component approach).
